### ISSUE TITLE
Alicezhao.com link is missing scheme; redirects to GitHub 404

### ISSUE THREAD

**Issue by SteGriff** [alicelovescake/alicelovescake#1]
Hi Alice -- nice personal readme!

Your link to alicezhao.com needs a scheme, otherwise the markdown parser thinks it's a relative URL 😱

I'll put in an edit now if you'd care to accept it?

Peace 🌱

Ste

**Comment by alicelovescake** [comment]
Thanks so much @SteGriff!! It's great to meet you and I appreciate the fix!
